export const authActions = {
  //Status Update
  STATUS_UPDATE_REQUEST: 'STATUS_UPDATE_REQUEST',
  STATUS_UPDATE_SUCCESS: 'STATUS_UPDATE_SUCCESS',
  //Status Update
  STATUS_VIEWED_SUCCESS: 'STATUS_VIEWED_SUCCESS',
};
